"""email insted of id

Revision ID: 19eff6e49c55
Revises: b797422a6f52
Create Date: 2023-06-06 23:32:58.346498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19eff6e49c55'
down_revision = 'b797422a6f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('userEmail', sa.String(length=256), nullable=False))
    op.drop_column('orders', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'userEmail')
    # ### end Alembic commands ###
